import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import { Playfair_Display } from 'next/font/google';
import '../styles/globals.css';

const interSans = Inter({
	variable: '--font-inter-sans',
	weight: ['100', '200', '300', '400', '500', '600', '700', '800', '900'],
	subsets: ['latin'],
});

const playfairDisplay = Playfair_Display({
	variable: '--font-playfair-display',
	weight: ['400', '500', '600', '700', '800'],
	subsets: ['latin'],
});

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang='en'>
			<body className={`${interSans.variable} ${playfairDisplay.variable}`}>
				{children}
			</body>
		</html>
	);
}
