/* tslint:disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:db-schema` to regenerate this file.
 */

import type {} from '@payloadcms/db-postgres'
import { relations } from '@payloadcms/db-postgres/drizzle'
import {
	boolean,
	foreignKey,
	index,
	integer,
	jsonb,
	numeric,
	pgEnum,
	pgTable,
	serial,
	timestamp,
	uniqueIndex,
	varchar,
	type AnyPgColumn,
} from '@payloadcms/db-postgres/drizzle/pg-core'
export const enum_pathways_processing_time_min_uom = pgEnum(
	'enum_pathways_processing_time_min_uom',
	['1', '7', '30.4583333333', '365']
)
export const enum_pathways_processing_time_max_uom = pgEnum(
	'enum_pathways_processing_time_max_uom',
	['1', '7', '30.4583333333', '365']
)
export const enum_pathways_duration_min_uom = pgEnum('enum_pathways_duration_min_uom', [
	'1',
	'7',
	'30.4583333333',
	'365',
])
export const enum_pathways_duration_max_uom = pgEnum('enum_pathways_duration_max_uom', [
	'1',
	'7',
	'30.4583333333',
	'365',
])
export const enum_users_timezone = pgEnum('enum_users_timezone', [
	'Africa/Abidjan',
	'Africa/Accra',
	'Africa/Addis_Ababa',
	'Africa/Algiers',
	'Africa/Asmera',
	'Africa/Bamako',
	'Africa/Bangui',
	'Africa/Banjul',
	'Africa/Bissau',
	'Africa/Blantyre',
	'Africa/Brazzaville',
	'Africa/Bujumbura',
	'Africa/Cairo',
	'Africa/Casablanca',
	'Africa/Ceuta',
	'Africa/Conakry',
	'Africa/Dakar',
	'Africa/Dar_es_Salaam',
	'Africa/Djibouti',
	'Africa/Douala',
	'Africa/El_Aaiun',
	'Africa/Freetown',
	'Africa/Gaborone',
	'Africa/Harare',
	'Africa/Johannesburg',
	'Africa/Juba',
	'Africa/Kampala',
	'Africa/Khartoum',
	'Africa/Kigali',
	'Africa/Kinshasa',
	'Africa/Lagos',
	'Africa/Libreville',
	'Africa/Lome',
	'Africa/Luanda',
	'Africa/Lubumbashi',
	'Africa/Lusaka',
	'Africa/Malabo',
	'Africa/Maputo',
	'Africa/Maseru',
	'Africa/Mbabane',
	'Africa/Mogadishu',
	'Africa/Monrovia',
	'Africa/Nairobi',
	'Africa/Ndjamena',
	'Africa/Niamey',
	'Africa/Nouakchott',
	'Africa/Ouagadougou',
	'Africa/Porto-Novo',
	'Africa/Sao_Tome',
	'Africa/Tripoli',
	'Africa/Tunis',
	'Africa/Windhoek',
	'America/Adak',
	'America/Anchorage',
	'America/Anguilla',
	'America/Antigua',
	'America/Araguaina',
	'America/Argentina/La_Rioja',
	'America/Argentina/Rio_Gallegos',
	'America/Argentina/Salta',
	'America/Argentina/San_Juan',
	'America/Argentina/San_Luis',
	'America/Argentina/Tucuman',
	'America/Argentina/Ushuaia',
	'America/Aruba',
	'America/Asuncion',
	'America/Bahia',
	'America/Bahia_Banderas',
	'America/Barbados',
	'America/Belem',
	'America/Belize',
	'America/Blanc-Sablon',
	'America/Boa_Vista',
	'America/Bogota',
	'America/Boise',
	'America/Buenos_Aires',
	'America/Cambridge_Bay',
	'America/Campo_Grande',
	'America/Cancun',
	'America/Caracas',
	'America/Catamarca',
	'America/Cayenne',
	'America/Cayman',
	'America/Chicago',
	'America/Chihuahua',
	'America/Ciudad_Juarez',
	'America/Coral_Harbour',
	'America/Cordoba',
	'America/Costa_Rica',
	'America/Coyhaique',
	'America/Creston',
	'America/Cuiaba',
	'America/Curacao',
	'America/Danmarkshavn',
	'America/Dawson',
	'America/Dawson_Creek',
	'America/Denver',
	'America/Detroit',
	'America/Dominica',
	'America/Edmonton',
	'America/Eirunepe',
	'America/El_Salvador',
	'America/Fort_Nelson',
	'America/Fortaleza',
	'America/Glace_Bay',
	'America/Godthab',
	'America/Goose_Bay',
	'America/Grand_Turk',
	'America/Grenada',
	'America/Guadeloupe',
	'America/Guatemala',
	'America/Guayaquil',
	'America/Guyana',
	'America/Halifax',
	'America/Havana',
	'America/Hermosillo',
	'America/Indiana/Knox',
	'America/Indiana/Marengo',
	'America/Indiana/Petersburg',
	'America/Indiana/Tell_City',
	'America/Indiana/Vevay',
	'America/Indiana/Vincennes',
	'America/Indiana/Winamac',
	'America/Indianapolis',
	'America/Inuvik',
	'America/Iqaluit',
	'America/Jamaica',
	'America/Jujuy',
	'America/Juneau',
	'America/Kentucky/Monticello',
	'America/Kralendijk',
	'America/La_Paz',
	'America/Lima',
	'America/Los_Angeles',
	'America/Louisville',
	'America/Lower_Princes',
	'America/Maceio',
	'America/Managua',
	'America/Manaus',
	'America/Marigot',
	'America/Martinique',
	'America/Matamoros',
	'America/Mazatlan',
	'America/Mendoza',
	'America/Menominee',
	'America/Merida',
	'America/Metlakatla',
	'America/Mexico_City',
	'America/Miquelon',
	'America/Moncton',
	'America/Monterrey',
	'America/Montevideo',
	'America/Montserrat',
	'America/Nassau',
	'America/New_York',
	'America/Nome',
	'America/Noronha',
	'America/North_Dakota/Beulah',
	'America/North_Dakota/Center',
	'America/North_Dakota/New_Salem',
	'America/Ojinaga',
	'America/Panama',
	'America/Paramaribo',
	'America/Phoenix',
	'America/Port-au-Prince',
	'America/Port_of_Spain',
	'America/Porto_Velho',
	'America/Puerto_Rico',
	'America/Punta_Arenas',
	'America/Rankin_Inlet',
	'America/Recife',
	'America/Regina',
	'America/Resolute',
	'America/Rio_Branco',
	'America/Santarem',
	'America/Santiago',
	'America/Santo_Domingo',
	'America/Sao_Paulo',
	'America/Scoresbysund',
	'America/Sitka',
	'America/St_Barthelemy',
	'America/St_Johns',
	'America/St_Kitts',
	'America/St_Lucia',
	'America/St_Thomas',
	'America/St_Vincent',
	'America/Swift_Current',
	'America/Tegucigalpa',
	'America/Thule',
	'America/Tijuana',
	'America/Toronto',
	'America/Tortola',
	'America/Vancouver',
	'America/Whitehorse',
	'America/Winnipeg',
	'America/Yakutat',
	'Antarctica/Casey',
	'Antarctica/Davis',
	'Antarctica/DumontDUrville',
	'Antarctica/Macquarie',
	'Antarctica/Mawson',
	'Antarctica/McMurdo',
	'Antarctica/Palmer',
	'Antarctica/Rothera',
	'Antarctica/Syowa',
	'Antarctica/Troll',
	'Antarctica/Vostok',
	'Arctic/Longyearbyen',
	'Asia/Aden',
	'Asia/Almaty',
	'Asia/Amman',
	'Asia/Anadyr',
	'Asia/Aqtau',
	'Asia/Aqtobe',
	'Asia/Ashgabat',
	'Asia/Atyrau',
	'Asia/Baghdad',
	'Asia/Bahrain',
	'Asia/Baku',
	'Asia/Bangkok',
	'Asia/Barnaul',
	'Asia/Beirut',
	'Asia/Bishkek',
	'Asia/Brunei',
	'Asia/Calcutta',
	'Asia/Chita',
	'Asia/Colombo',
	'Asia/Damascus',
	'Asia/Dhaka',
	'Asia/Dili',
	'Asia/Dubai',
	'Asia/Dushanbe',
	'Asia/Famagusta',
	'Asia/Gaza',
	'Asia/Hebron',
	'Asia/Hong_Kong',
	'Asia/Hovd',
	'Asia/Irkutsk',
	'Asia/Jakarta',
	'Asia/Jayapura',
	'Asia/Jerusalem',
	'Asia/Kabul',
	'Asia/Kamchatka',
	'Asia/Karachi',
	'Asia/Katmandu',
	'Asia/Khandyga',
	'Asia/Krasnoyarsk',
	'Asia/Kuala_Lumpur',
	'Asia/Kuching',
	'Asia/Kuwait',
	'Asia/Macau',
	'Asia/Magadan',
	'Asia/Makassar',
	'Asia/Manila',
	'Asia/Muscat',
	'Asia/Nicosia',
	'Asia/Novokuznetsk',
	'Asia/Novosibirsk',
	'Asia/Omsk',
	'Asia/Oral',
	'Asia/Phnom_Penh',
	'Asia/Pontianak',
	'Asia/Pyongyang',
	'Asia/Qatar',
	'Asia/Qostanay',
	'Asia/Qyzylorda',
	'Asia/Rangoon',
	'Asia/Riyadh',
	'Asia/Saigon',
	'Asia/Sakhalin',
	'Asia/Samarkand',
	'Asia/Seoul',
	'Asia/Shanghai',
	'Asia/Singapore',
	'Asia/Srednekolymsk',
	'Asia/Taipei',
	'Asia/Tashkent',
	'Asia/Tbilisi',
	'Asia/Tehran',
	'Asia/Thimphu',
	'Asia/Tokyo',
	'Asia/Tomsk',
	'Asia/Ulaanbaatar',
	'Asia/Urumqi',
	'Asia/Ust-Nera',
	'Asia/Vientiane',
	'Asia/Vladivostok',
	'Asia/Yakutsk',
	'Asia/Yekaterinburg',
	'Asia/Yerevan',
	'Atlantic/Azores',
	'Atlantic/Bermuda',
	'Atlantic/Canary',
	'Atlantic/Cape_Verde',
	'Atlantic/Faeroe',
	'Atlantic/Madeira',
	'Atlantic/Reykjavik',
	'Atlantic/South_Georgia',
	'Atlantic/St_Helena',
	'Atlantic/Stanley',
	'Australia/Adelaide',
	'Australia/Brisbane',
	'Australia/Broken_Hill',
	'Australia/Darwin',
	'Australia/Eucla',
	'Australia/Hobart',
	'Australia/Lindeman',
	'Australia/Lord_Howe',
	'Australia/Melbourne',
	'Australia/Perth',
	'Australia/Sydney',
	'Europe/Amsterdam',
	'Europe/Andorra',
	'Europe/Astrakhan',
	'Europe/Athens',
	'Europe/Belgrade',
	'Europe/Berlin',
	'Europe/Bratislava',
	'Europe/Brussels',
	'Europe/Bucharest',
	'Europe/Budapest',
	'Europe/Busingen',
	'Europe/Chisinau',
	'Europe/Copenhagen',
	'Europe/Dublin',
	'Europe/Gibraltar',
	'Europe/Guernsey',
	'Europe/Helsinki',
	'Europe/Isle_of_Man',
	'Europe/Istanbul',
	'Europe/Jersey',
	'Europe/Kaliningrad',
	'Europe/Kiev',
	'Europe/Kirov',
	'Europe/Lisbon',
	'Europe/Ljubljana',
	'Europe/London',
	'Europe/Luxembourg',
	'Europe/Madrid',
	'Europe/Malta',
	'Europe/Mariehamn',
	'Europe/Minsk',
	'Europe/Monaco',
	'Europe/Moscow',
	'Europe/Oslo',
	'Europe/Paris',
	'Europe/Podgorica',
	'Europe/Prague',
	'Europe/Riga',
	'Europe/Rome',
	'Europe/Samara',
	'Europe/San_Marino',
	'Europe/Sarajevo',
	'Europe/Saratov',
	'Europe/Simferopol',
	'Europe/Skopje',
	'Europe/Sofia',
	'Europe/Stockholm',
	'Europe/Tallinn',
	'Europe/Tirane',
	'Europe/Ulyanovsk',
	'Europe/Vaduz',
	'Europe/Vatican',
	'Europe/Vienna',
	'Europe/Vilnius',
	'Europe/Volgograd',
	'Europe/Warsaw',
	'Europe/Zagreb',
	'Europe/Zurich',
	'Indian/Antananarivo',
	'Indian/Chagos',
	'Indian/Christmas',
	'Indian/Cocos',
	'Indian/Comoro',
	'Indian/Kerguelen',
	'Indian/Mahe',
	'Indian/Maldives',
	'Indian/Mauritius',
	'Indian/Mayotte',
	'Indian/Reunion',
	'Pacific/Apia',
	'Pacific/Auckland',
	'Pacific/Bougainville',
	'Pacific/Chatham',
	'Pacific/Easter',
	'Pacific/Efate',
	'Pacific/Enderbury',
	'Pacific/Fakaofo',
	'Pacific/Fiji',
	'Pacific/Funafuti',
	'Pacific/Galapagos',
	'Pacific/Gambier',
	'Pacific/Guadalcanal',
	'Pacific/Guam',
	'Pacific/Honolulu',
	'Pacific/Kiritimati',
	'Pacific/Kosrae',
	'Pacific/Kwajalein',
	'Pacific/Majuro',
	'Pacific/Marquesas',
	'Pacific/Midway',
	'Pacific/Nauru',
	'Pacific/Niue',
	'Pacific/Norfolk',
	'Pacific/Noumea',
	'Pacific/Pago_Pago',
	'Pacific/Palau',
	'Pacific/Pitcairn',
	'Pacific/Ponape',
	'Pacific/Port_Moresby',
	'Pacific/Rarotonga',
	'Pacific/Saipan',
	'Pacific/Tahiti',
	'Pacific/Tarawa',
	'Pacific/Tongatapu',
	'Pacific/Truk',
	'Pacific/Wake',
	'Pacific/Wallis',
])

export const countries = pgTable(
	'countries',
	{
		id: varchar('id').primaryKey(),
		name: varchar('name').notNull(),
		updatedAt: timestamp('updated_at', { mode: 'string', withTimezone: true, precision: 3 })
			.defaultNow()
			.notNull(),
		createdAt: timestamp('created_at', { mode: 'string', withTimezone: true, precision: 3 })
			.defaultNow()
			.notNull(),
	},
	columns => [
		uniqueIndex('countries_name_idx').on(columns.name),
		index('countries_updated_at_idx').on(columns.updatedAt),
		index('countries_created_at_idx').on(columns.createdAt),
	]
)

export const countries_rels = pgTable(
	'countries_rels',
	{
		id: serial('id').primaryKey(),
		order: integer('order'),
		parent: varchar('parent_id').notNull(),
		path: varchar('path').notNull(),
		languagesID: varchar('languages_id'),
		currenciesID: varchar('currencies_id'),
	},
	columns => [
		index('countries_rels_order_idx').on(columns.order),
		index('countries_rels_parent_idx').on(columns.parent),
		index('countries_rels_path_idx').on(columns.path),
		index('countries_rels_languages_id_idx').on(columns.languagesID),
		index('countries_rels_currencies_id_idx').on(columns.currenciesID),
		foreignKey({
			columns: [columns['parent']],
			foreignColumns: [countries.id],
			name: 'countries_rels_parent_fk',
		}).onDelete('cascade'),
		foreignKey({
			columns: [columns['languagesID']],
			foreignColumns: [languages.id],
			name: 'countries_rels_languages_fk',
		}).onDelete('cascade'),
		foreignKey({
			columns: [columns['currenciesID']],
			foreignColumns: [currencies.id],
			name: 'countries_rels_currencies_fk',
		}).onDelete('cascade'),
	]
)

export const currencies = pgTable(
	'currencies',
	{
		id: varchar('id').primaryKey(),
		name: varchar('name').notNull(),
		symbol: varchar('symbol').notNull(),
		updatedAt: timestamp('updated_at', { mode: 'string', withTimezone: true, precision: 3 })
			.defaultNow()
			.notNull(),
		createdAt: timestamp('created_at', { mode: 'string', withTimezone: true, precision: 3 })
			.defaultNow()
			.notNull(),
	},
	columns => [
		uniqueIndex('currencies_name_idx').on(columns.name),
		index('currencies_updated_at_idx').on(columns.updatedAt),
		index('currencies_created_at_idx').on(columns.createdAt),
	]
)

export const languages = pgTable(
	'languages',
	{
		id: varchar('id').primaryKey(),
		name: varchar('name').notNull(),
		updatedAt: timestamp('updated_at', { mode: 'string', withTimezone: true, precision: 3 })
			.defaultNow()
			.notNull(),
		createdAt: timestamp('created_at', { mode: 'string', withTimezone: true, precision: 3 })
			.defaultNow()
			.notNull(),
	},
	columns => [
		uniqueIndex('languages_name_idx').on(columns.name),
		index('languages_updated_at_idx').on(columns.updatedAt),
		index('languages_created_at_idx').on(columns.createdAt),
	]
)

export const media = pgTable(
	'media',
	{
		id: serial('id').primaryKey(),
		alt: varchar('alt').notNull(),
		updatedAt: timestamp('updated_at', { mode: 'string', withTimezone: true, precision: 3 })
			.defaultNow()
			.notNull(),
		createdAt: timestamp('created_at', { mode: 'string', withTimezone: true, precision: 3 })
			.defaultNow()
			.notNull(),
		url: varchar('url'),
		thumbnailURL: varchar('thumbnail_u_r_l'),
		filename: varchar('filename'),
		mimeType: varchar('mime_type'),
		filesize: numeric('filesize', { mode: 'number' }),
		width: numeric('width', { mode: 'number' }),
		height: numeric('height', { mode: 'number' }),
		focalX: numeric('focal_x', { mode: 'number' }),
		focalY: numeric('focal_y', { mode: 'number' }),
	},
	columns => [
		index('media_updated_at_idx').on(columns.updatedAt),
		index('media_created_at_idx').on(columns.createdAt),
		uniqueIndex('media_filename_idx').on(columns.filename),
	]
)

export const pathways_notes = pgTable(
	'pathways_notes',
	{
		_order: integer('_order').notNull(),
		_parentID: integer('_parent_id').notNull(),
		id: varchar('id').primaryKey(),
		note: varchar('note'),
	},
	columns => [
		index('pathways_notes_order_idx').on(columns._order),
		index('pathways_notes_parent_id_idx').on(columns._parentID),
		foreignKey({
			columns: [columns['_parentID']],
			foreignColumns: [pathways.id],
			name: 'pathways_notes_parent_id_fk',
		}).onDelete('cascade'),
	]
)

export const pathways_documentation_documents = pgTable(
	'pathways_documentation_documents',
	{
		_order: integer('_order').notNull(),
		_parentID: integer('_parent_id').notNull(),
		id: varchar('id').primaryKey(),
		required: boolean('required').default(false),
		type: integer('type_id')
			.notNull()
			.references(() => pathway_documents.id, {
				onDelete: 'set null',
			}),
		name: varchar('name').notNull(),
		link: varchar('link'),
		cost: numeric('cost', { mode: 'number' }),
		notes: varchar('notes'),
	},
	columns => [
		index('pathways_documentation_documents_order_idx').on(columns._order),
		index('pathways_documentation_documents_parent_id_idx').on(columns._parentID),
		index('pathways_documentation_documents_type_idx').on(columns.type),
		foreignKey({
			columns: [columns['_parentID']],
			foreignColumns: [pathways.id],
			name: 'pathways_documentation_documents_parent_id_fk',
		}).onDelete('cascade'),
	]
)

export const pathways = pgTable(
	'pathways',
	{
		id: serial('id').primaryKey(),
		country: varchar('country_id')
			.notNull()
			.references(() => countries.id, {
				onDelete: 'set null',
			}),
		name: varchar('name').notNull(),
		link: varchar('link').notNull(),
		description: varchar('description').notNull(),
		processingTime_na: boolean('processing_time_na').default(false),
		processingTime_minQty: numeric('processing_time_min_qty', { mode: 'number' })
			.notNull()
			.default(0),
		processingTime_minUom: enum_pathways_processing_time_min_uom('processing_time_min_uom')
			.notNull()
			.default('1'),
		processingTime_maxQty: numeric('processing_time_max_qty', { mode: 'number' })
			.notNull()
			.default(0),
		processingTime_maxUom:
			enum_pathways_processing_time_max_uom('processing_time_max_uom').default('1'),
		processingTime_minMaxEqual: boolean('processing_time_min_max_equal').default(false),
		processingTime_sameUOM: boolean('processing_time_same_u_o_m').default(false),
		duration_na: boolean('duration_na').default(false),
		duration_minQty: numeric('duration_min_qty', { mode: 'number' }).notNull().default(0),
		duration_minUom: enum_pathways_duration_min_uom('duration_min_uom').notNull().default('1'),
		duration_maxQty: numeric('duration_max_qty', { mode: 'number' }).notNull().default(0),
		duration_maxUom: enum_pathways_duration_max_uom('duration_max_uom').default('1'),
		duration_minMaxEqual: boolean('duration_min_max_equal').default(false),
		duration_sameUOM: boolean('duration_same_u_o_m').default(false),
		cost_na: boolean('cost_na').default(false),
		cost_minQty: numeric('cost_min_qty', { mode: 'number' }).notNull().default(0),
		cost_maxQty: numeric('cost_max_qty', { mode: 'number' }).notNull().default(0),
		cost_currency: varchar('cost_currency_id').references(() => currencies.id, {
			onDelete: 'set null',
		}),
		cost_minMaxEqual: boolean('cost_min_max_equal').default(false),
		renewable: boolean('renewable'),
		citizenshipPathway: boolean('citizenship_pathway'),
		residencyPathway: boolean('residency_pathway'),
		reunificationPathway: boolean('reunification_pathway'),
		updatedAt: timestamp('updated_at', { mode: 'string', withTimezone: true, precision: 3 })
			.defaultNow()
			.notNull(),
		createdAt: timestamp('created_at', { mode: 'string', withTimezone: true, precision: 3 })
			.defaultNow()
			.notNull(),
	},
	columns => [
		index('pathways_country_idx').on(columns.country),
		uniqueIndex('pathways_name_idx').on(columns.name),
		index('pathways_cost_cost_currency_idx').on(columns.cost_currency),
		index('pathways_updated_at_idx').on(columns.updatedAt),
		index('pathways_created_at_idx').on(columns.createdAt),
	]
)

export const pathway_documents = pgTable(
	'pathway_documents',
	{
		id: serial('id').primaryKey(),
		title: varchar('title').notNull(),
		description: varchar('description'),
		updatedAt: timestamp('updated_at', { mode: 'string', withTimezone: true, precision: 3 })
			.defaultNow()
			.notNull(),
		createdAt: timestamp('created_at', { mode: 'string', withTimezone: true, precision: 3 })
			.defaultNow()
			.notNull(),
	},
	columns => [
		index('pathway_documents_updated_at_idx').on(columns.updatedAt),
		index('pathway_documents_created_at_idx').on(columns.createdAt),
	]
)

export const roles = pgTable(
	'roles',
	{
		id: serial('id').primaryKey(),
		name: varchar('name').notNull(),
		updatedAt: timestamp('updated_at', { mode: 'string', withTimezone: true, precision: 3 })
			.defaultNow()
			.notNull(),
		createdAt: timestamp('created_at', { mode: 'string', withTimezone: true, precision: 3 })
			.defaultNow()
			.notNull(),
	},
	columns => [
		uniqueIndex('roles_name_idx').on(columns.name),
		index('roles_updated_at_idx').on(columns.updatedAt),
		index('roles_created_at_idx').on(columns.createdAt),
	]
)

export const teams = pgTable(
	'teams',
	{
		id: serial('id').primaryKey(),
		name: varchar('name').notNull(),
		parentTeam: integer('parent_team_id').references((): AnyPgColumn => teams.id, {
			onDelete: 'set null',
		}),
		collections_countries: boolean('collections_countries'),
		collections_currencies: boolean('collections_currencies'),
		collections_languages: boolean('collections_languages'),
		collections_media: boolean('collections_media'),
		collections_pathways: boolean('collections_pathways'),
		collections_pathwayDocuments: boolean('collections_pathway_documents'),
		collections_roles: boolean('collections_roles'),
		collections_teams: boolean('collections_teams'),
		collections_users: boolean('collections_users'),
		collections_guides: boolean('collections_guides'),
		updatedAt: timestamp('updated_at', { mode: 'string', withTimezone: true, precision: 3 })
			.defaultNow()
			.notNull(),
		createdAt: timestamp('created_at', { mode: 'string', withTimezone: true, precision: 3 })
			.defaultNow()
			.notNull(),
	},
	columns => [
		uniqueIndex('teams_name_idx').on(columns.name),
		index('teams_parent_team_idx').on(columns.parentTeam),
		index('teams_updated_at_idx').on(columns.updatedAt),
		index('teams_created_at_idx').on(columns.createdAt),
	]
)

export const users_sessions = pgTable(
	'users_sessions',
	{
		_order: integer('_order').notNull(),
		_parentID: integer('_parent_id').notNull(),
		id: varchar('id').primaryKey(),
		createdAt: timestamp('created_at', { mode: 'string', withTimezone: true, precision: 3 }),
		expiresAt: timestamp('expires_at', {
			mode: 'string',
			withTimezone: true,
			precision: 3,
		}).notNull(),
	},
	columns => [
		index('users_sessions_order_idx').on(columns._order),
		index('users_sessions_parent_id_idx').on(columns._parentID),
		foreignKey({
			columns: [columns['_parentID']],
			foreignColumns: [users.id],
			name: 'users_sessions_parent_id_fk',
		}).onDelete('cascade'),
	]
)

export const users = pgTable(
	'users',
	{
		id: serial('id').primaryKey(),
		firstName: varchar('first_name'),
		lastName: varchar('last_name'),
		timezone: enum_users_timezone('timezone'),
		discordHandle: varchar('discord_handle'),
		pronouns_he: boolean('pronouns_he'),
		pronouns_him: boolean('pronouns_him'),
		pronouns_his: boolean('pronouns_his'),
		pronouns_she: boolean('pronouns_she'),
		pronouns_her: boolean('pronouns_her'),
		pronouns_hers: boolean('pronouns_hers'),
		pronouns_they: boolean('pronouns_they'),
		pronouns_them: boolean('pronouns_them'),
		pronouns_theirs: boolean('pronouns_theirs'),
		updatedAt: timestamp('updated_at', { mode: 'string', withTimezone: true, precision: 3 })
			.defaultNow()
			.notNull(),
		createdAt: timestamp('created_at', { mode: 'string', withTimezone: true, precision: 3 })
			.defaultNow()
			.notNull(),
		email: varchar('email').notNull(),
		username: varchar('username').notNull(),
		resetPasswordToken: varchar('reset_password_token'),
		resetPasswordExpiration: timestamp('reset_password_expiration', {
			mode: 'string',
			withTimezone: true,
			precision: 3,
		}),
		salt: varchar('salt'),
		hash: varchar('hash'),
		loginAttempts: numeric('login_attempts', { mode: 'number' }).default(0),
		lockUntil: timestamp('lock_until', { mode: 'string', withTimezone: true, precision: 3 }),
	},
	columns => [
		index('users_updated_at_idx').on(columns.updatedAt),
		index('users_created_at_idx').on(columns.createdAt),
		uniqueIndex('users_email_idx').on(columns.email),
		uniqueIndex('users_username_idx').on(columns.username),
	]
)

export const guides = pgTable(
	'guides',
	{
		id: serial('id').primaryKey(),
		title: varchar('title').notNull(),
		subtitle: varchar('subtitle'),
		eyebrow: varchar('eyebrow'),
		updatedAt: timestamp('updated_at', { mode: 'string', withTimezone: true, precision: 3 })
			.defaultNow()
			.notNull(),
		createdAt: timestamp('created_at', { mode: 'string', withTimezone: true, precision: 3 })
			.defaultNow()
			.notNull(),
	},
	columns => [
		index('guides_updated_at_idx').on(columns.updatedAt),
		index('guides_created_at_idx').on(columns.createdAt),
	]
)

export const payload_kv = pgTable(
	'payload_kv',
	{
		id: serial('id').primaryKey(),
		key: varchar('key').notNull(),
		data: jsonb('data').notNull(),
	},
	columns => [uniqueIndex('payload_kv_key_idx').on(columns.key)]
)

export const payload_locked_documents = pgTable(
	'payload_locked_documents',
	{
		id: serial('id').primaryKey(),
		globalSlug: varchar('global_slug'),
		updatedAt: timestamp('updated_at', { mode: 'string', withTimezone: true, precision: 3 })
			.defaultNow()
			.notNull(),
		createdAt: timestamp('created_at', { mode: 'string', withTimezone: true, precision: 3 })
			.defaultNow()
			.notNull(),
	},
	columns => [
		index('payload_locked_documents_global_slug_idx').on(columns.globalSlug),
		index('payload_locked_documents_updated_at_idx').on(columns.updatedAt),
		index('payload_locked_documents_created_at_idx').on(columns.createdAt),
	]
)

export const payload_locked_documents_rels = pgTable(
	'payload_locked_documents_rels',
	{
		id: serial('id').primaryKey(),
		order: integer('order'),
		parent: integer('parent_id').notNull(),
		path: varchar('path').notNull(),
		countriesID: varchar('countries_id'),
		currenciesID: varchar('currencies_id'),
		languagesID: varchar('languages_id'),
		mediaID: integer('media_id'),
		pathwaysID: integer('pathways_id'),
		pathwayDocumentsID: integer('pathway_documents_id'),
		rolesID: integer('roles_id'),
		teamsID: integer('teams_id'),
		usersID: integer('users_id'),
		guidesID: integer('guides_id'),
	},
	columns => [
		index('payload_locked_documents_rels_order_idx').on(columns.order),
		index('payload_locked_documents_rels_parent_idx').on(columns.parent),
		index('payload_locked_documents_rels_path_idx').on(columns.path),
		index('payload_locked_documents_rels_countries_id_idx').on(columns.countriesID),
		index('payload_locked_documents_rels_currencies_id_idx').on(columns.currenciesID),
		index('payload_locked_documents_rels_languages_id_idx').on(columns.languagesID),
		index('payload_locked_documents_rels_media_id_idx').on(columns.mediaID),
		index('payload_locked_documents_rels_pathways_id_idx').on(columns.pathwaysID),
		index('payload_locked_documents_rels_pathway_documents_id_idx').on(columns.pathwayDocumentsID),
		index('payload_locked_documents_rels_roles_id_idx').on(columns.rolesID),
		index('payload_locked_documents_rels_teams_id_idx').on(columns.teamsID),
		index('payload_locked_documents_rels_users_id_idx').on(columns.usersID),
		index('payload_locked_documents_rels_guides_id_idx').on(columns.guidesID),
		foreignKey({
			columns: [columns['parent']],
			foreignColumns: [payload_locked_documents.id],
			name: 'payload_locked_documents_rels_parent_fk',
		}).onDelete('cascade'),
		foreignKey({
			columns: [columns['countriesID']],
			foreignColumns: [countries.id],
			name: 'payload_locked_documents_rels_countries_fk',
		}).onDelete('cascade'),
		foreignKey({
			columns: [columns['currenciesID']],
			foreignColumns: [currencies.id],
			name: 'payload_locked_documents_rels_currencies_fk',
		}).onDelete('cascade'),
		foreignKey({
			columns: [columns['languagesID']],
			foreignColumns: [languages.id],
			name: 'payload_locked_documents_rels_languages_fk',
		}).onDelete('cascade'),
		foreignKey({
			columns: [columns['mediaID']],
			foreignColumns: [media.id],
			name: 'payload_locked_documents_rels_media_fk',
		}).onDelete('cascade'),
		foreignKey({
			columns: [columns['pathwaysID']],
			foreignColumns: [pathways.id],
			name: 'payload_locked_documents_rels_pathways_fk',
		}).onDelete('cascade'),
		foreignKey({
			columns: [columns['pathwayDocumentsID']],
			foreignColumns: [pathway_documents.id],
			name: 'payload_locked_documents_rels_pathway_documents_fk',
		}).onDelete('cascade'),
		foreignKey({
			columns: [columns['rolesID']],
			foreignColumns: [roles.id],
			name: 'payload_locked_documents_rels_roles_fk',
		}).onDelete('cascade'),
		foreignKey({
			columns: [columns['teamsID']],
			foreignColumns: [teams.id],
			name: 'payload_locked_documents_rels_teams_fk',
		}).onDelete('cascade'),
		foreignKey({
			columns: [columns['usersID']],
			foreignColumns: [users.id],
			name: 'payload_locked_documents_rels_users_fk',
		}).onDelete('cascade'),
		foreignKey({
			columns: [columns['guidesID']],
			foreignColumns: [guides.id],
			name: 'payload_locked_documents_rels_guides_fk',
		}).onDelete('cascade'),
	]
)

export const payload_preferences = pgTable(
	'payload_preferences',
	{
		id: serial('id').primaryKey(),
		key: varchar('key'),
		value: jsonb('value'),
		updatedAt: timestamp('updated_at', { mode: 'string', withTimezone: true, precision: 3 })
			.defaultNow()
			.notNull(),
		createdAt: timestamp('created_at', { mode: 'string', withTimezone: true, precision: 3 })
			.defaultNow()
			.notNull(),
	},
	columns => [
		index('payload_preferences_key_idx').on(columns.key),
		index('payload_preferences_updated_at_idx').on(columns.updatedAt),
		index('payload_preferences_created_at_idx').on(columns.createdAt),
	]
)

export const payload_preferences_rels = pgTable(
	'payload_preferences_rels',
	{
		id: serial('id').primaryKey(),
		order: integer('order'),
		parent: integer('parent_id').notNull(),
		path: varchar('path').notNull(),
		usersID: integer('users_id'),
	},
	columns => [
		index('payload_preferences_rels_order_idx').on(columns.order),
		index('payload_preferences_rels_parent_idx').on(columns.parent),
		index('payload_preferences_rels_path_idx').on(columns.path),
		index('payload_preferences_rels_users_id_idx').on(columns.usersID),
		foreignKey({
			columns: [columns['parent']],
			foreignColumns: [payload_preferences.id],
			name: 'payload_preferences_rels_parent_fk',
		}).onDelete('cascade'),
		foreignKey({
			columns: [columns['usersID']],
			foreignColumns: [users.id],
			name: 'payload_preferences_rels_users_fk',
		}).onDelete('cascade'),
	]
)

export const payload_migrations = pgTable(
	'payload_migrations',
	{
		id: serial('id').primaryKey(),
		name: varchar('name'),
		batch: numeric('batch', { mode: 'number' }),
		updatedAt: timestamp('updated_at', { mode: 'string', withTimezone: true, precision: 3 })
			.defaultNow()
			.notNull(),
		createdAt: timestamp('created_at', { mode: 'string', withTimezone: true, precision: 3 })
			.defaultNow()
			.notNull(),
	},
	columns => [
		index('payload_migrations_updated_at_idx').on(columns.updatedAt),
		index('payload_migrations_created_at_idx').on(columns.createdAt),
	]
)

export const relations_countries_rels = relations(countries_rels, ({ one }) => ({
	parent: one(countries, {
		fields: [countries_rels.parent],
		references: [countries.id],
		relationName: '_rels',
	}),
	languagesID: one(languages, {
		fields: [countries_rels.languagesID],
		references: [languages.id],
		relationName: 'languages',
	}),
	currenciesID: one(currencies, {
		fields: [countries_rels.currenciesID],
		references: [currencies.id],
		relationName: 'currencies',
	}),
}))
export const relations_countries = relations(countries, ({ many }) => ({
	_rels: many(countries_rels, {
		relationName: '_rels',
	}),
}))
export const relations_currencies = relations(currencies, () => ({}))
export const relations_languages = relations(languages, () => ({}))
export const relations_media = relations(media, () => ({}))
export const relations_pathways_notes = relations(pathways_notes, ({ one }) => ({
	_parentID: one(pathways, {
		fields: [pathways_notes._parentID],
		references: [pathways.id],
		relationName: 'notes',
	}),
}))
export const relations_pathways_documentation_documents = relations(
	pathways_documentation_documents,
	({ one }) => ({
		_parentID: one(pathways, {
			fields: [pathways_documentation_documents._parentID],
			references: [pathways.id],
			relationName: 'documentation_documents',
		}),
		type: one(pathway_documents, {
			fields: [pathways_documentation_documents.type],
			references: [pathway_documents.id],
			relationName: 'type',
		}),
	})
)
export const relations_pathways = relations(pathways, ({ one, many }) => ({
	country: one(countries, {
		fields: [pathways.country],
		references: [countries.id],
		relationName: 'country',
	}),
	notes: many(pathways_notes, {
		relationName: 'notes',
	}),
	cost_currency: one(currencies, {
		fields: [pathways.cost_currency],
		references: [currencies.id],
		relationName: 'cost_currency',
	}),
	documentation_documents: many(pathways_documentation_documents, {
		relationName: 'documentation_documents',
	}),
}))
export const relations_pathway_documents = relations(pathway_documents, () => ({}))
export const relations_roles = relations(roles, () => ({}))
export const relations_teams = relations(teams, ({ one }) => ({
	parentTeam: one(teams, {
		fields: [teams.parentTeam],
		references: [teams.id],
		relationName: 'parentTeam',
	}),
}))
export const relations_users_sessions = relations(users_sessions, ({ one }) => ({
	_parentID: one(users, {
		fields: [users_sessions._parentID],
		references: [users.id],
		relationName: 'sessions',
	}),
}))
export const relations_users = relations(users, ({ many }) => ({
	sessions: many(users_sessions, {
		relationName: 'sessions',
	}),
}))
export const relations_guides = relations(guides, () => ({}))
export const relations_payload_kv = relations(payload_kv, () => ({}))
export const relations_payload_locked_documents_rels = relations(
	payload_locked_documents_rels,
	({ one }) => ({
		parent: one(payload_locked_documents, {
			fields: [payload_locked_documents_rels.parent],
			references: [payload_locked_documents.id],
			relationName: '_rels',
		}),
		countriesID: one(countries, {
			fields: [payload_locked_documents_rels.countriesID],
			references: [countries.id],
			relationName: 'countries',
		}),
		currenciesID: one(currencies, {
			fields: [payload_locked_documents_rels.currenciesID],
			references: [currencies.id],
			relationName: 'currencies',
		}),
		languagesID: one(languages, {
			fields: [payload_locked_documents_rels.languagesID],
			references: [languages.id],
			relationName: 'languages',
		}),
		mediaID: one(media, {
			fields: [payload_locked_documents_rels.mediaID],
			references: [media.id],
			relationName: 'media',
		}),
		pathwaysID: one(pathways, {
			fields: [payload_locked_documents_rels.pathwaysID],
			references: [pathways.id],
			relationName: 'pathways',
		}),
		pathwayDocumentsID: one(pathway_documents, {
			fields: [payload_locked_documents_rels.pathwayDocumentsID],
			references: [pathway_documents.id],
			relationName: 'pathwayDocuments',
		}),
		rolesID: one(roles, {
			fields: [payload_locked_documents_rels.rolesID],
			references: [roles.id],
			relationName: 'roles',
		}),
		teamsID: one(teams, {
			fields: [payload_locked_documents_rels.teamsID],
			references: [teams.id],
			relationName: 'teams',
		}),
		usersID: one(users, {
			fields: [payload_locked_documents_rels.usersID],
			references: [users.id],
			relationName: 'users',
		}),
		guidesID: one(guides, {
			fields: [payload_locked_documents_rels.guidesID],
			references: [guides.id],
			relationName: 'guides',
		}),
	})
)
export const relations_payload_locked_documents = relations(
	payload_locked_documents,
	({ many }) => ({
		_rels: many(payload_locked_documents_rels, {
			relationName: '_rels',
		}),
	})
)
export const relations_payload_preferences_rels = relations(
	payload_preferences_rels,
	({ one }) => ({
		parent: one(payload_preferences, {
			fields: [payload_preferences_rels.parent],
			references: [payload_preferences.id],
			relationName: '_rels',
		}),
		usersID: one(users, {
			fields: [payload_preferences_rels.usersID],
			references: [users.id],
			relationName: 'users',
		}),
	})
)
export const relations_payload_preferences = relations(payload_preferences, ({ many }) => ({
	_rels: many(payload_preferences_rels, {
		relationName: '_rels',
	}),
}))
export const relations_payload_migrations = relations(payload_migrations, () => ({}))

type DatabaseSchema = {
	enum_pathways_processing_time_min_uom: typeof enum_pathways_processing_time_min_uom
	enum_pathways_processing_time_max_uom: typeof enum_pathways_processing_time_max_uom
	enum_pathways_duration_min_uom: typeof enum_pathways_duration_min_uom
	enum_pathways_duration_max_uom: typeof enum_pathways_duration_max_uom
	enum_users_timezone: typeof enum_users_timezone
	countries: typeof countries
	countries_rels: typeof countries_rels
	currencies: typeof currencies
	languages: typeof languages
	media: typeof media
	pathways_notes: typeof pathways_notes
	pathways_documentation_documents: typeof pathways_documentation_documents
	pathways: typeof pathways
	pathway_documents: typeof pathway_documents
	roles: typeof roles
	teams: typeof teams
	users_sessions: typeof users_sessions
	users: typeof users
	guides: typeof guides
	payload_kv: typeof payload_kv
	payload_locked_documents: typeof payload_locked_documents
	payload_locked_documents_rels: typeof payload_locked_documents_rels
	payload_preferences: typeof payload_preferences
	payload_preferences_rels: typeof payload_preferences_rels
	payload_migrations: typeof payload_migrations
	relations_countries_rels: typeof relations_countries_rels
	relations_countries: typeof relations_countries
	relations_currencies: typeof relations_currencies
	relations_languages: typeof relations_languages
	relations_media: typeof relations_media
	relations_pathways_notes: typeof relations_pathways_notes
	relations_pathways_documentation_documents: typeof relations_pathways_documentation_documents
	relations_pathways: typeof relations_pathways
	relations_pathway_documents: typeof relations_pathway_documents
	relations_roles: typeof relations_roles
	relations_teams: typeof relations_teams
	relations_users_sessions: typeof relations_users_sessions
	relations_users: typeof relations_users
	relations_guides: typeof relations_guides
	relations_payload_kv: typeof relations_payload_kv
	relations_payload_locked_documents_rels: typeof relations_payload_locked_documents_rels
	relations_payload_locked_documents: typeof relations_payload_locked_documents
	relations_payload_preferences_rels: typeof relations_payload_preferences_rels
	relations_payload_preferences: typeof relations_payload_preferences
	relations_payload_migrations: typeof relations_payload_migrations
}

declare module '@payloadcms/db-postgres' {
	export interface GeneratedDatabaseSchema {
		schema: DatabaseSchema
	}
}
